main:
	g++ -std=c++11 -Wall -pedantic-errors -g Main.cpp  Tool.cpp Tool.hpp Paper.hpp Paper.cpp Rock.hpp Rock.cpp Scissors.hpp Scissors.cpp RPS_Game.hpp RPS_Game.cpp -o main

clean:
	\rm -f main *.o 


	
